// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yswvdavntaevzbxluvkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzd3ZkYXZudGFldnpieGx1dmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTE4MTAsImV4cCI6MjA3OTQ1MTgxMH0.Zt-dvXDIv8P5UTqi16fgKq4zPqA5LjtDPHu6MR0RnWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);