// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vbnkhhrlgszewrswyksz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibmtoaHJsZ3N6ZXdyc3d5a3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMzYxNzMsImV4cCI6MjA3OTcxMjE3M30.7lNW_Me0jCTjlHCZtSDl3IQwtTzntR6GR9hAeXEyFWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);